steps:
  # Docker Build
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "northamerica-northeast2-docker.pkg.dev/portfolio-site-472419/portfolio-repo-smit/portfolio-smit-image:latest",
        ".",
      ]
    id: Build Container Image

  # Docker Push
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "northamerica-northeast2-docker.pkg.dev/portfolio-site-472419/portfolio-repo-smit/portfolio-smit-image:latest",
      ]
    id: Push Container Image to Artifact Repo

  # Create GKE Cluster (only if not exists)
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        if ! gcloud container clusters describe portfolio-cluster-smit --zone=northamerica-northeast2 --project=portfolio-site-472419 >/dev/null 2>&1; then
          echo "Cluster not found. Creating..."
          gcloud container clusters create portfolio-cluster-smit \
            --zone=northamerica-northeast2 \
            --num-nodes=1 \
            --machine-type=e2-medium \
            --disk-type=pd-standard \
            --project=portfolio-site-472419
        else
          echo "Cluster already exists. Skipping creation."
        fi
    id: Create GKE Cluster (Conditional)

  # Get GKE Credentials
  - name: gcr.io/cloud-builders/gcloud
    args:
      - container
      - clusters
      - get-credentials
      - portfolio-cluster-smit
      - "--zone=northamerica-northeast2"
      - "--project=portfolio-site-472419"
    id: Get GKE Credentials

images:
  - "northamerica-northeast2-docker.pkg.dev/portfolio-site-472419/portfolio-repo-smit/portfolio-smit-image:latest"

options:
  logging: CLOUD_LOGGING_ONLY
